//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotebookApplication_hymanCorop
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> rolesID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UsersLogin UsersLogin { get; set; }
    }
}
